name: Run examples
'on':
  push:
    branches:
      - master
  pull_request: {}
defaults:
  run:
    shell: bash
jobs:
  terragrunt:
    name: Terragrunt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.35.9
      - name: Setup Infracost
        uses: ./setup
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Run Infracost
        run: >-
          infracost breakdown --path=examples/terragrunt/code --format=json
          --out-file=/tmp/infracost_breakdown.json
      - name: Generate Infracost comment
        run: >-
          infracost output --path=/tmp/infracost_breakdown.json
          --format=github-comment --out-file=/tmp/infracost_comment.md
      - name: Check the comment
        run: diff /tmp/infracost_comment.md ./testdata/terragrunt_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES != 'true'
      - name: Update the golden comment file
        run: cp /tmp/infracost_comment.md ./testdata/terragrunt_comment_golden.md
        if: env.UPDATE_GOLDEN_FILES == 'true'
